### ISSUE TITLE
JW embeds and footer

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/commencement.uiowa.edu#34]
To replicate create a new page and add a jw embed. The footer is missing for some reason.

See: http://commencement.uiowa.edu.dd:8083/test

**Comment by briand44** [comment]
This should be fixed now. https://github.com/ITS-UofIowa/commencement.uiowa.edu/commit/d365da627f2ca454b01891cc4d779b0f97f96d09#diff-fa930e02c3f27a0821a4d7647303b35fR31

https://api.drupal.org/comment/58888#comment-58888

`Self-closing syntax ("/>") used on a non-void HTML element. Ignoring the slash and treating as a start tag.
From line 161, column 94 to line 161, column 277
Code Extract:
jw-embed"<iframe src="https://content.jwplatform.com/players/OgIJ4QbF-7EaCFiXK.html" width="100%" height="100%" frameborder="0" scrolling="auto" allowfullscreen="" style="position:absolute;" />↩</di`
